#!/bin/sh

echo "###############################################################################"
echo "# Script Summary:                                                             #"
echo "# Author:                  yu.zuo                                             #"
echo "# Update Date:             2020.04.07                                         #"
echo "# Script version:          1.0.0                                              #"
echo "# Url: https://github.com/AsteriskZuo/ffmpeg_build_scripts                    #"
echo "#                                                                             #"
echo "# Brief introduction:                                                         #"
echo "# This script show help document.                                             #"
echo "#                                                                             #"
echo "# Prerequisites:                                                              #"
echo "# GNU bash (version 3.2.57 test success on macOS)                             #"
echo "#                                                                             #"
echo "# Reference:                                                                  #"
echo "# Url: http://yasm.tortall.net/                                               #"
echo "# Url: https://developer.android.com/ndk/guides/cmake                         #"
echo "# Url: https://developer.android.com/ndk/guides/abis                          #"
echo "# Url: https://developer.android.com/ndk/guides/other_build_systems           #"
echo "# Url: https://developer.android.com/ndk/guides/standalone_toolchain          #"
echo "# Url: https://gcc.gnu.org/onlinedocs/gcc/index.html                          #"
echo "# Url: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html #                                                        #"
echo "# Url: https://www.gnu.org/software/automake/manual/automake.html             #"
echo "# Url: https://llvm.org/docs/genindex.html                                    #"
echo "# Url: https://clang.llvm.org/                                                #"
echo "# Url: https://releases.llvm.org/10.0.0/tools/clang/docs/index.html           #"
echo "# Url: https://releases.llvm.org/10.0.0/tools/clang/docs/CrossCompilation.html #"
echo "# Url: https://github.com/libav/gas-preprocessor                              #"
echo "# Url: https://github.com/nldzsz/ffmpeg-build-scripts                         #"
echo "# Url: https://github.com/kewlbear/FFmpeg-iOS-build-script                    #"
echo "###############################################################################"